name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Setup mingw-w64
        run: |
          echo "[+] Install mingw-w64"
          sudo apt update
          sudo apt install mingw-w64 -y
          echo "[+] Check mingw-w64"
          x86_64-w64-mingw32-gcc -v
          echo "[+] Check make"
          make -v
          echo "[+] Check project file"
          ls
          echo "[+] Run make"
          make
          echo "[+] Compress beacon"
          zip -r dist.zip dist
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          tag_name: v1.0
          files: |
            dist.zip

