name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Setup mingw-w64
        run: |
          apt update
          apt install mingw-w64 -y
          x86_64-w64-mingw32-gcc -v
          make -v
      - name: Build by make
        run: |
          cd ${{ github.workspace }}
          make
          zip -r dist.zip dist
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          tag_name: v1.0
          files: |
            dist.zip

